name: Spawn
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup tmux
        run: |
          cp ./.tmux.conf $HOME/
      - name: Setup upterm session
        uses: owenthereal/action-upterm@v1
      - name: Run
        run: |
          echo test
