name: Spawn Linux aarch64
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Setup terminal configuration
        run: |
          cp ./.tmux.conf $HOME/
          cp ./.inputrc $HOME/
      - name: Setup SSH and Cloudflare Tunnel
        run: |
          mkdir -p ~/.ssh/
          chmod 700 ~/.ssh/
          echo "${{ secrets.MY_PUB_KEY }}" >> ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/authorized_keys
          ls -al ~/.ssh/
          cat ~/.ssh/authorized_keys
          wget https://github.com/cloudflare/cloudflared/releases/download/2026.2.0/cloudflared-linux-arm64.deb
          sudo dpkg -i cloudflared-linux-arm64.deb
          # mv cloudflared-linux-arm64 cloudflared
          # chmod +x cloudflared
          cloudflared tunnel run --token "${{ secrets.CLOUDFLARE_TUNNEL_TOKEN_LINUX_AARCH64 }}"
