name: Spawn
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup tmux
        run: |
          cp ./.tmux.conf $HOME/
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3          
      - name: Run
        run: |
          echo test
